### ISSUE TITLE
Support for more complex selectors

### ISSUE THREAD

**Issue by kevinkace** [maltsev/posthtml-inline-css#6]
Is there a goal to add support for more complex selectors, eg: `.parent .child` or `.element:first-child`?

**Comment by maltsev** [comment]
I use [posthtml-match-helper](https://github.com/rasmusfl0e/posthtml-match-helper) to select tags. Try to create an issue there. If this feature will be implemented then my plugin will support complex selectors too.

Meanwhile, you can use [juice](https://github.com/Automattic/juice/), which supports those selectors.

**Comment by kevinkace** [comment]
Thanks for the background, I'll check with `posthtml-match-helper`.
